= API & Entity

== Overview
REST-Сервисы и Сущности проекта

=== Version information
Version: 1.0

=== Contact information
Contact: start@igov.org.ua

Terms of service: https://github.com/e-government-ua/i/wiki

=== URI scheme
Host: localhost
BasePath: /

=== Tags

* SubjectContactType: Работа с типами контактов
* SubjectMessageCommonController -- Сообщения субьектов: Subject Message Common Controller
* FinanceCommonController -- Финансы общие (в т.ч. платежи): Finance Common Controller
* DictionaryController — Обработка csv-файлов без бд: Dictionary Common Controller
* DebugCentralController -- Дебаг и тест центральный: Debug Controller
* MUController -- контроллер для взаимодействия с веб сервисом министерства юстиции: MU Controller
* ActionItemController - Предметы действий (каталог сервисов): Action Item Controller
* ProcessChatController — Организация взаимосвязей чата: Process Chat Common Controller
* ActionFeedBackController — Действия фидбэков: Action Feed Back Common Controller
* ECPCommonController -- наложение электронной подписи: ECP Common Controller
* SubjectAccountType: Типы аккаунтов
* BackupController — Создание бэкапа данных таблицы ActGeBytearray: Backup Common Controller
* ProcessLinkCommonController — работа с внешними тасками: Process Link Common Controller
* AccessCommonController — Доступ общий (права доступов к сервисам): Access Common Controller
* ActionFlowController — Действия очередей (слоты потока, расписания и тикеты): Action Flow Common Controller
* SubjectMessageController -- Сообщения субьектов: Subject Message Controller
* DocumentAccessController -- Доступы к документам: Document Access Controller
* ProcessSubjectController — Иерархия процессов: Process Subject Common Controller
* ObjectPlaceCommonController -- Обьекты мест (населенных пунктов и регионов) и стран: Object Place Common Controller
* SubjectHuman: Subject Group Controller
* ActionIdentityCommonController: Action Identity Common Controller
* ActionTaskCommonController — Действия общие задач: Action Task Common Controller
* DocumentController -- Документы и смежные сущности: Document Controller
* SubjectGroup: Subject Group Controller
* с — Действия эскалаций: Action Escalation Common Controller
* ObjectFileCommonController -- Обьекты файлов общие: Object File Common Controller
* SubjectGroupController — Организационная иерархия: Subject Group Common Controller
* SubjectOrgan: Subject Group Controller
* FinanceCentralController -- Финансовые и смежные сущности: Finance Central Controller
* ExportCommonController -- вызов стороннего АПИ: Export Common Controller
* RelationController — Обработка Relation: Relation Common Controller
* SubjectController - субъекты  и смежные сущности: Subject Controller
* ActionExecuteController: Action Execute Controller
* DocumentImageController -- Накладывание ЭЦП на независимые документы: Document Image Common Controller
* ActionHistoryController -- История по документам: Action History Common Controller
* SubjectCommonController — Организационная иерархия: Subject Common Controller
* DocumentCommonController -- Проверки наложености ЭЦП по строкам-подписантам: Document Common Controller
* SubjectHumanPositionCustom: Работа с должностями сотрудников
* ActionTaskCentralController -- Действия задачи центрально: Action Task Controller
* ActionEventController -- События по действиям и статистика: Action Event Common Controller
* Server: Server Controller
* ProcessCommonController — организация процессов: Process Common Controller
* Subject: Subject Group Controller
* SubjectHumanRole: Subject Human Role Controller
* AccessCentralController -- Доступ центральный: Access Controller
* SubjectContact: Управление сотрудниками
* DebugCommonController - Дебаг и тест общий: Debug Common Controller
* EmailCommonController — Отправление сообщений: Email Common Controller
* ObjectController -- Обьекты и смежные сущности: Object Common Controller


