= Activiti's API & Entity

== Overview
REST-Сервисы и Сущности - Activiti

=== Contact information

Terms of service: https://www.activiti.org/userguide/

=== URI scheme
Host: localhost
BasePath: /

=== Tags

* historic-process-instance-identity-link-collection-resource: Historic Process Instance Identity Link Collection Resource
* task-comment-resource: Task Comment Resource
* task-identity-link-collection-resource: Task Identity Link Collection Resource
* task-variable-collection-resource: Task Variable Collection Resource
* task-comment-collection-resource: Task Comment Collection Resource
* historic-process-instance-variable-data-resource: Historic Process Instance Variable Data Resource
* deployment-resource-resource: Deployment Resource Resource
* user-collection-resource: User Collection Resource
* job-resource: Job Resource
* historic-detail-data-resource: Historic Detail Data Resource
* task-identity-link-family-resource: Task Identity Link Family Resource
* historic-activity-instance-query-resource: Historic Activity Instance Query Resource
* historic-variable-instance-collection-resource: Historic Variable Instance Collection Resource
* process-definition-model-resource: Process Definition Model Resource
* process-instance-identity-link-collection-resource: Process Instance Identity Link Collection Resource
* process-definition-collection-resource: Process Definition Collection Resource
* process-definition-image-resource: Process Definition Image Resource
* table-collection-resource: Table Collection Resource
* simple-workflow-resource: Simple Workflow Resource
* group-resource: Group Resource
* table-data-resource: Table Data Resource
* user-resource: User Resource
* historic-process-instance-collection-resource: Historic Process Instance Collection Resource
* historic-task-instance-identity-link-collection-resource: Historic Task Instance Identity Link Collection Resource
* execution-resource: Execution Resource
* historic-process-instance-query-resource: Historic Process Instance Query Resource
* process-instance-variable-data-resource: Process Instance Variable Data Resource
* process-instance-collection-resource: Process Instance Collection Resource
* process-instance-variable-collection-resource: Process Instance Variable Collection Resource
* historic-process-instance-comment-resource: Historic Process Instance Comment Resource
* historic-task-instance-resource: Historic Task Instance Resource
* model-collection-resource: Model Collection Resource
* form-data-resource: Form Data Resource
* process-definition-properties-resource: Process Definition Properties Resource
* process-instance-diagram-resource: Process Instance Diagram Resource
* execution-collection-resource: Execution Collection Resource
* historic-task-instance-collection-resource: Historic Task Instance Collection Resource
* historic-detail-query-resource: Historic Detail Query Resource
* process-instance-variable-resource: Process Instance Variable Resource
* task-variable-data-resource: Task Variable Data Resource
* task-event-collection-resource: Task Event Collection Resource
* deployment-collection-resource: Deployment Collection Resource
* historic-variable-instance-query-resource: Historic Variable Instance Query Resource
* deployment-resource: Deployment Resource
* execution-query-resource: Execution Query Resource
* group-membership-collection-resource: Group Membership Collection Resource
* deployment-resource-data-resource: Deployment Resource Data Resource
* group-membership-resource: Group Membership Resource
* process-definition-resource-data-resource: Process Definition Resource Data Resource
* process-instance-resource: Process Instance Resource
* process-definition-resource: Process Definition Resource
* execution-variable-resource: Execution Variable Resource
* historic-process-instance-comment-collection-resource: Historic Process Instance Comment Collection Resource
* process-definition-identity-link-collection-resource: Process Definition Identity Link Collection Resource
* process-definition-identity-link-resource: Process Definition Identity Link Resource
* deployment-resource-collection-resource: Deployment Resource Collection Resource
* historic-detail-collection-resource: Historic Detail Collection Resource
* historic-process-instance-resource: Historic Process Instance Resource
* historic-variable-instance-data-resource: Historic Variable Instance Data Resource
* model-source-resource: Model Source Resource
* task-event-resource: Task Event Resource
* execution-variable-collection-resource: Execution Variable Collection Resource
* execution-variable-data-resource: Execution Variable Data Resource
* historic-activity-instance-collection-resource: Historic Activity Instance Collection Resource
* historic-task-instance-variable-data-resource: Historic Task Instance Variable Data Resource
* table-columns-resource: Table Columns Resource
* properties-collection-resource: Properties Collection Resource
* table-resource: Table Resource
* job-exception-stacktrace-resource: Job Exception Stacktrace Resource
* task-sub-task-collection-resource: Task Sub Task Collection Resource
* task-attachment-collection-resource: Task Attachment Collection Resource
* task-variable-resource: Task Variable Resource
* process-instance-identity-link-resource: Process Instance Identity Link Resource
* group-collection-resource: Group Collection Resource
* task-identity-link-resource: Task Identity Link Resource
* task-query-resource: Task Query Resource
* model-source-extra-resource: Model Source Extra Resource
* user-info-collection-resource: User Info Collection Resource
* task-collection-resource: Task Collection Resource
* job-collection-resource: Job Collection Resource
* user-picture-resource: User Picture Resource
* model-resource: Model Resource
* process-instance-query-resource: Process Instance Query Resource
* user-info-resource: User Info Resource
* task-attachment-content-resource: Task Attachment Content Resource
* task-attachment-resource: Task Attachment Resource
* process-engine-resource: Process Engine Resource
* signal-resource: Signal Resource
* task-resource: Task Resource
* execution-active-activities-collection-resource: Execution Active Activities Collection Resource
* historic-task-instance-query-resource: Historic Task Instance Query Resource


